"""initial schema

Revision ID: fd27d12e791e
Revises: 
Create Date: 2026-01-14 13:25:49.054290+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd27d12e791e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('unique_users', sa.Integer(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_date', 'metric_type', 'tenant_id', name='uq_activity_metric_date_type')
    )
    op.create_index('ix_activity_metrics_date', 'activity_metrics', ['metric_date'], unique=False)
    op.create_index('ix_activity_metrics_tenant_id', 'activity_metrics', ['tenant_id'], unique=False)
    op.create_index('ix_activity_metrics_type', 'activity_metrics', ['metric_type'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('entity_class', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=True),
    sa.Column('max_depth', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['entities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', 'tenant_id', name='uq_entities_slug_tenant')
    )
    op.create_index('ix_entities_class_type', 'entities', ['entity_class', 'entity_type'], unique=False)
    op.create_index('ix_entities_name', 'entities', ['name'], unique=False)
    op.create_index('ix_entities_parent_id', 'entities', ['parent_id'], unique=False)
    op.create_index('ix_entities_slug', 'entities', ['slug'], unique=False)
    op.create_index('ix_entities_status', 'entities', ['status'], unique=False)
    op.create_index('ix_entities_tenant_id', 'entities', ['tenant_id'], unique=False)
    op.create_table('permission_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'tenant_id', name='uq_permission_tags_name_tenant')
    )
    op.create_index('ix_permission_tags_name', 'permission_tags', ['name'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('resource', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'tenant_id', name='uq_permissions_name_tenant')
    )
    op.create_index('ix_permissions_is_active', 'permissions', ['is_active'], unique=False)
    op.create_index('ix_permissions_is_system', 'permissions', ['is_system'], unique=False)
    op.create_index('ix_permissions_name', 'permissions', ['name'], unique=False)
    op.create_index('ix_permissions_resource', 'permissions', ['resource'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('auth_methods', postgresql.ARRAY(sa.String(length=50)), server_default='{PASSWORD}', nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('suspended_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_password_change', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_verification_token', sa.String(length=255), nullable=True),
    sa.Column('email_verification_expires', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'tenant_id', name='uq_users_email_tenant')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_status', 'users', ['status'], unique=False)
    op.create_index('ix_users_tenant_id', 'users', ['tenant_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_hour', sa.Integer(), nullable=True),
    sa.Column('rate_limit_per_day', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('inherit_from_tree', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prefix'),
    sa.UniqueConstraint('prefix', name='uq_api_keys_prefix')
    )
    op.create_index('ix_api_keys_expires_at', 'api_keys', ['expires_at'], unique=False)
    op.create_index('ix_api_keys_owner_id', 'api_keys', ['owner_id'], unique=False)
    op.create_index('ix_api_keys_prefix', 'api_keys', ['prefix'], unique=False)
    op.create_index('ix_api_keys_status', 'api_keys', ['status'], unique=False)
    op.create_index('ix_api_keys_tenant_id', 'api_keys', ['tenant_id'], unique=False)
    op.create_table('entity_closure',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('ancestor_id', sa.UUID(), nullable=False),
    sa.Column('descendant_id', sa.UUID(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ancestor_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['descendant_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ancestor_id', 'descendant_id', name='uq_entity_closure')
    )
    op.create_index('ix_closure_ancestor_depth', 'entity_closure', ['ancestor_id', 'depth'], unique=False)
    op.create_index('ix_closure_ancestor_id', 'entity_closure', ['ancestor_id'], unique=False)
    op.create_index('ix_closure_descendant_depth', 'entity_closure', ['descendant_id', 'depth'], unique=False)
    op.create_index('ix_closure_descendant_id', 'entity_closure', ['descendant_id'], unique=False)
    op.create_index('ix_closure_tenant_id', 'entity_closure', ['tenant_id'], unique=False)
    op.create_table('entity_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('joined_by_id', sa.UUID(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_id', sa.UUID(), nullable=True),
    sa.Column('revocation_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['joined_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['revoked_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entity_id', name='uq_entity_membership')
    )
    op.create_index('ix_em_entity_id', 'entity_memberships', ['entity_id'], unique=False)
    op.create_index('ix_em_status', 'entity_memberships', ['status'], unique=False)
    op.create_index('ix_em_tenant_id', 'entity_memberships', ['tenant_id'], unique=False)
    op.create_index('ix_em_user_id', 'entity_memberships', ['user_id'], unique=False)
    op.create_index('ix_em_user_status', 'entity_memberships', ['user_id', 'status'], unique=False)
    op.create_index('ix_em_valid_until', 'entity_memberships', ['valid_until'], unique=False)
    op.create_table('login_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('login_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('success', sa.String(length=10), nullable=False),
    sa.Column('auth_method', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_login_history_success', 'login_history', ['success'], unique=False)
    op.create_index('ix_login_history_tenant_id', 'login_history', ['tenant_id'], unique=False)
    op.create_index('ix_login_history_timestamp', 'login_history', ['login_at'], unique=False)
    op.create_index('ix_login_history_user_id', 'login_history', ['user_id'], unique=False)
    op.create_table('oauth_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('redirect_uri', sa.String(length=2000), nullable=True),
    sa.Column('code_verifier', sa.String(length=255), nullable=True),
    sa.Column('nonce', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state')
    )
    op.create_index('ix_oauth_states_expires_at', 'oauth_states', ['expires_at'], unique=False)
    op.create_index('ix_oauth_states_state', 'oauth_states', ['state'], unique=False)
    op.create_index('ix_oauth_states_tenant_id', 'oauth_states', ['tenant_id'], unique=False)
    op.create_table('permission_tag_links',
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['permission_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('permission_id', 'tag_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=255), nullable=True),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    sa.UniqueConstraint('token_hash', name='uq_refresh_tokens_hash')
    )
    op.create_index('ix_refresh_tokens_device', 'refresh_tokens', ['device_fingerprint'], unique=False)
    op.create_index('ix_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('ix_refresh_tokens_is_revoked', 'refresh_tokens', ['is_revoked'], unique=False)
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_roles_entity_id', 'roles', ['entity_id'], unique=False)
    op.create_index('ix_roles_is_global', 'roles', ['is_global'], unique=False)
    op.create_index('ix_roles_name', 'roles', ['name'], unique=False)
    op.create_index('ix_roles_name_tenant', 'roles', ['name', 'tenant_id'], unique=False)
    op.create_table('social_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=255), nullable=True),
    sa.Column('provider_username', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=2000), nullable=True),
    sa.Column('profile_url', sa.String(length=2000), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_social_provider_user')
    )
    op.create_index('ix_social_accounts_provider', 'social_accounts', ['provider'], unique=False)
    op.create_index('ix_social_accounts_tenant_id', 'social_accounts', ['tenant_id'], unique=False)
    op.create_index('ix_social_accounts_user_id', 'social_accounts', ['user_id'], unique=False)
    op.create_table('user_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('api_call_count', sa.Integer(), nullable=False),
    sa.Column('action_count', sa.Integer(), nullable=False),
    sa.Column('first_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'activity_date', name='uq_user_activity_date')
    )
    op.create_index('ix_user_activities_date', 'user_activities', ['activity_date'], unique=False)
    op.create_index('ix_user_activities_tenant_id', 'user_activities', ['tenant_id'], unique=False)
    op.create_index('ix_user_activities_user_id', 'user_activities', ['user_id'], unique=False)
    op.create_table('api_key_ip_whitelist',
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('api_key_id', 'ip_address')
    )
    op.create_index('ix_api_key_ip_key_id', 'api_key_ip_whitelist', ['api_key_id'], unique=False)
    op.create_table('api_key_scopes',
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('api_key_id', 'scope')
    )
    op.create_index('ix_api_key_scopes_key_id', 'api_key_scopes', ['api_key_id'], unique=False)
    op.create_table('condition_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('permission_id', sa.UUID(), nullable=True),
    sa.Column('operator', sa.String(length=5), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('parent_group_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['parent_group_id'], ['condition_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_condition_groups_permission_id', 'condition_groups', ['permission_id'], unique=False)
    op.create_index('ix_condition_groups_role_id', 'condition_groups', ['role_id'], unique=False)
    op.create_table('entity_membership_roles',
    sa.Column('membership_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['entity_memberships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('membership_id', 'role_id')
    )
    op.create_index('ix_emr_membership_id', 'entity_membership_roles', ['membership_id'], unique=False)
    op.create_index('ix_emr_role_id', 'entity_membership_roles', ['role_id'], unique=False)
    op.create_table('role_entity_type_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_retp_entity_type', 'role_entity_type_permissions', ['entity_type'], unique=False)
    op.create_index('ix_retp_role_entity_type', 'role_entity_type_permissions', ['role_id', 'entity_type'], unique=False)
    op.create_index('ix_retp_role_id', 'role_entity_type_permissions', ['role_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_index('ix_role_permissions_permission_id', 'role_permissions', ['permission_id'], unique=False)
    op.create_index('ix_role_permissions_role_id', 'role_permissions', ['role_id'], unique=False)
    op.create_table('user_role_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assigned_by_id', sa.UUID(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_id', sa.UUID(), nullable=True),
    sa.Column('revocation_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['revoked_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role_membership')
    )
    op.create_index('ix_urm_role_id', 'user_role_memberships', ['role_id'], unique=False)
    op.create_index('ix_urm_status', 'user_role_memberships', ['status'], unique=False)
    op.create_index('ix_urm_tenant_id', 'user_role_memberships', ['tenant_id'], unique=False)
    op.create_index('ix_urm_user_id', 'user_role_memberships', ['user_id'], unique=False)
    op.create_index('ix_urm_user_status', 'user_role_memberships', ['user_id', 'status'], unique=False)
    op.create_index('ix_urm_valid_until', 'user_role_memberships', ['valid_until'], unique=False)
    op.create_table('permission_conditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('condition_group_id', sa.UUID(), nullable=True),
    sa.Column('attribute', sa.String(length=200), nullable=False),
    sa.Column('operator', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['condition_group_id'], ['condition_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_permission_conditions_group_id', 'permission_conditions', ['condition_group_id'], unique=False)
    op.create_index('ix_permission_conditions_permission_id', 'permission_conditions', ['permission_id'], unique=False)
    op.create_table('role_conditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('condition_group_id', sa.UUID(), nullable=True),
    sa.Column('attribute', sa.String(length=200), nullable=False),
    sa.Column('operator', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['condition_group_id'], ['condition_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_role_conditions_group_id', 'role_conditions', ['condition_group_id'], unique=False)
    op.create_index('ix_role_conditions_role_id', 'role_conditions', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_role_conditions_role_id', table_name='role_conditions')
    op.drop_index('ix_role_conditions_group_id', table_name='role_conditions')
    op.drop_table('role_conditions')
    op.drop_index('ix_permission_conditions_permission_id', table_name='permission_conditions')
    op.drop_index('ix_permission_conditions_group_id', table_name='permission_conditions')
    op.drop_table('permission_conditions')
    op.drop_index('ix_urm_valid_until', table_name='user_role_memberships')
    op.drop_index('ix_urm_user_status', table_name='user_role_memberships')
    op.drop_index('ix_urm_user_id', table_name='user_role_memberships')
    op.drop_index('ix_urm_tenant_id', table_name='user_role_memberships')
    op.drop_index('ix_urm_status', table_name='user_role_memberships')
    op.drop_index('ix_urm_role_id', table_name='user_role_memberships')
    op.drop_table('user_role_memberships')
    op.drop_index('ix_role_permissions_role_id', table_name='role_permissions')
    op.drop_index('ix_role_permissions_permission_id', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('ix_retp_role_id', table_name='role_entity_type_permissions')
    op.drop_index('ix_retp_role_entity_type', table_name='role_entity_type_permissions')
    op.drop_index('ix_retp_entity_type', table_name='role_entity_type_permissions')
    op.drop_table('role_entity_type_permissions')
    op.drop_index('ix_emr_role_id', table_name='entity_membership_roles')
    op.drop_index('ix_emr_membership_id', table_name='entity_membership_roles')
    op.drop_table('entity_membership_roles')
    op.drop_index('ix_condition_groups_role_id', table_name='condition_groups')
    op.drop_index('ix_condition_groups_permission_id', table_name='condition_groups')
    op.drop_table('condition_groups')
    op.drop_index('ix_api_key_scopes_key_id', table_name='api_key_scopes')
    op.drop_table('api_key_scopes')
    op.drop_index('ix_api_key_ip_key_id', table_name='api_key_ip_whitelist')
    op.drop_table('api_key_ip_whitelist')
    op.drop_index('ix_user_activities_user_id', table_name='user_activities')
    op.drop_index('ix_user_activities_tenant_id', table_name='user_activities')
    op.drop_index('ix_user_activities_date', table_name='user_activities')
    op.drop_table('user_activities')
    op.drop_index('ix_social_accounts_user_id', table_name='social_accounts')
    op.drop_index('ix_social_accounts_tenant_id', table_name='social_accounts')
    op.drop_index('ix_social_accounts_provider', table_name='social_accounts')
    op.drop_table('social_accounts')
    op.drop_index('ix_roles_name_tenant', table_name='roles')
    op.drop_index('ix_roles_name', table_name='roles')
    op.drop_index('ix_roles_is_global', table_name='roles')
    op.drop_index('ix_roles_entity_id', table_name='roles')
    op.drop_table('roles')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_is_revoked', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_device', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('permission_tag_links')
    op.drop_index('ix_oauth_states_tenant_id', table_name='oauth_states')
    op.drop_index('ix_oauth_states_state', table_name='oauth_states')
    op.drop_index('ix_oauth_states_expires_at', table_name='oauth_states')
    op.drop_table('oauth_states')
    op.drop_index('ix_login_history_user_id', table_name='login_history')
    op.drop_index('ix_login_history_timestamp', table_name='login_history')
    op.drop_index('ix_login_history_tenant_id', table_name='login_history')
    op.drop_index('ix_login_history_success', table_name='login_history')
    op.drop_table('login_history')
    op.drop_index('ix_em_valid_until', table_name='entity_memberships')
    op.drop_index('ix_em_user_status', table_name='entity_memberships')
    op.drop_index('ix_em_user_id', table_name='entity_memberships')
    op.drop_index('ix_em_tenant_id', table_name='entity_memberships')
    op.drop_index('ix_em_status', table_name='entity_memberships')
    op.drop_index('ix_em_entity_id', table_name='entity_memberships')
    op.drop_table('entity_memberships')
    op.drop_index('ix_closure_tenant_id', table_name='entity_closure')
    op.drop_index('ix_closure_descendant_id', table_name='entity_closure')
    op.drop_index('ix_closure_descendant_depth', table_name='entity_closure')
    op.drop_index('ix_closure_ancestor_id', table_name='entity_closure')
    op.drop_index('ix_closure_ancestor_depth', table_name='entity_closure')
    op.drop_table('entity_closure')
    op.drop_index('ix_api_keys_tenant_id', table_name='api_keys')
    op.drop_index('ix_api_keys_status', table_name='api_keys')
    op.drop_index('ix_api_keys_prefix', table_name='api_keys')
    op.drop_index('ix_api_keys_owner_id', table_name='api_keys')
    op.drop_index('ix_api_keys_expires_at', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index('ix_users_tenant_id', table_name='users')
    op.drop_index('ix_users_status', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_permissions_resource', table_name='permissions')
    op.drop_index('ix_permissions_name', table_name='permissions')
    op.drop_index('ix_permissions_is_system', table_name='permissions')
    op.drop_index('ix_permissions_is_active', table_name='permissions')
    op.drop_table('permissions')
    op.drop_index('ix_permission_tags_name', table_name='permission_tags')
    op.drop_table('permission_tags')
    op.drop_index('ix_entities_tenant_id', table_name='entities')
    op.drop_index('ix_entities_status', table_name='entities')
    op.drop_index('ix_entities_slug', table_name='entities')
    op.drop_index('ix_entities_parent_id', table_name='entities')
    op.drop_index('ix_entities_name', table_name='entities')
    op.drop_index('ix_entities_class_type', table_name='entities')
    op.drop_table('entities')
    op.drop_index('ix_activity_metrics_type', table_name='activity_metrics')
    op.drop_index('ix_activity_metrics_tenant_id', table_name='activity_metrics')
    op.drop_index('ix_activity_metrics_date', table_name='activity_metrics')
    op.drop_table('activity_metrics')
    # ### end Alembic commands ###
