services:
  api:
    build: .
    container_name: outlabs_auth_api
    ports:
      - "8030:8030"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=mongodb://host.docker.internal:27017
      - MONGO_DATABASE=outlabsAuth_test
      - REDIS_URL=redis://:guest@host.docker.internal:6379
      - SECRET_KEY=a_very_secret_key_that_should_be_changed_in_production
      - ACCESS_TOKEN_EXPIRE_MINUTES=15
      - REFRESH_TOKEN_EXPIRE_DAYS=30
      - ALGORITHM=HS256
    command: uvicorn api.main:app --host 0.0.0.0 --port 8030 --reload

  # admin-ui:
  #   build:
  #     context: ./admin-ui
  #     dockerfile: Dockerfile
  #   container_name: outlabs_auth_admin_ui
  #   ports:
  #     - "8088:80"
  #   depends_on:
  #     - api
  #   environment:
  #     - VITE_API_BASE_URL=http://localhost:8030
